// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  article: dynamic(() => import("./Article")),
  rich_text: dynamic(() => import("./RichText")),
};
